name: build-and-upload accounts ms
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: build the jar file and upload to s3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build project with Maven
        run: mvn -B package --file pom.xml

